name: gocast
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # A simple Service Locator.
  get_it: ^5.0.6
  # BLoC Design Pattern (Business Logic Component)
  bloc: ^6.1.1
  # Widgets that make it easy to integrate blocs and cubits into Flutter.
  flutter_bloc: ^6.1.2
  # Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS and SharedPreferences on Android.
  shared_preferences: ^2.0.6
  # Introduction/Onboarding package for flutter app with some customizations possibilities.
  introduction_screen: ^1.0.9
  # A widget provided to the flutter scroll component drop-down refresh and pull up load.
  pull_to_refresh: ^1.6.4
  # Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.0.0
  # Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
  share: ^0.6.5+4
  # A composable, Future-based library for making HTTP requests.
  http: ^0.13.3
  # Provides APIs for debugging and error logging.
  logging: ^1.0.1
  # Native dart package for logging appenders usable with the logging package.
  logging_appenders: ^1.0.0
  # Dart implementation of sprintf.
  sprintf: ^5.0.0
  # Plugin to detect whether the current device is an emulator or a simulator.
  flutter_is_emulator: ^1.0.0
  # A package provides an easy way to add shimmer effect in Flutter project.
  shimmer: ^1.1.2
  # Being able to compare objects in Dart often involves having to override the == operator as well as hashCode.
  equatable: ^2.0.0
  # Draw SVG (and some Android VectorDrawable (XML)) files on a Flutter Widget.
  flutter_svg: ^0.22.0
  # A flutter list that allows scrolling to a specific item in the list.
  scrollable_positioned_list: ^0.1.10
  # Widget that only shows the first lines of a text and adds a link to expand the full text.
  expandable_text: ^2.1.0
  # A feature-rich audio player for Flutter. Loop, clip and concatenate any sound from any source (asset/file/URL/stream) in a variety of audio formats with gapless playback.
  just_audio: ^0.7.5
  # Sets the iOS audio session category and Android audio attributes for your app, and manages your app's audio focus, mixing and ducking behaviour.
  audio_session: ^0.1.2
  # Slidable list item with directional slide actions that can be dismissed.
  flutter_slidable: ^0.6.0
  # Show alert dialog or modal action sheet adaptively according to platform.
  adaptive_dialog: ^1.0.0
  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes.
  url_launcher: ^6.0.6
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data/
    - assets/images/
    - assets/images/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: L10n # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en
